### PR TITLE
Use data attribute to set loading state

### PR DESCRIPTION
**Pull request by dustinbrownman**
We ran into an issue using this with the Treehouse app. We had a featurette that needed to clone the element to a new location on the DOM (and destroy the original). In the cloning process, however, we lose any expando properties (e.g. `featurette` and `featuretteLoading`).

This adjusts `Featurette.load` to use a data attribute to keep track of the loading state. so now, the element will have `data-featurette-loading="true"`, which will persist even if cloned.

It'd probably be a good idea to attach the featurette itself to a data element, but since `data-featurette` was already in use, I decided to focus solely on ensuring we don't try and reload already loaded featurettes.

### CODE REVIEW

**Comment by commondream** [comment]
That use case doesn't sound like it's what Featurette's intended for. I'd recommend writing that code elsewhere rather than duplicating a Featurette node.

**Comment by dustinbrownman** [comment]
To be more explicit, it's actually something that is done in a third-party library. It has to do with the limitations of moving DOM elements around on mobile Safari. So instead of moving the element, they clone, append, and remove the original. Because of this, if the featurette attempts to reload (`Featurette.load()`), it'll end in an infinite loop. It's certainly an edge case, but one that has come up several times.

But regardless of that, switching to data attributes seems to be an improvement. The fact that `.cloneNode` doesn't copy over expando attributes is a sign that they probably shouldn't be holding information about state. At least in my opinion :)

I'll see if I can get Andrew Olsen to give his two cents. He recommended opening up a PR to patch this.

**Comment by commondream** [comment]
We chose to use a js property on the element explicitly because Featurette is intended to be a bit of code attached to the Dom element. Removing and cloning the Dom element should destroy the Featurette and require that a new one be created.

**Comment by dustinbrownman** [comment]
That's a really good point. I adjust the tests to better reflect the use case we're seeing. The issue is that the featurette isn't really destroyed as you describe above. When the element is cloned, the code continues to execute, and if somewhere that featurette calls `Featurette.load()`, it will then see that newly cloned DOM element with `data-featurette="something"`, load it (because the newly cloned element doesn't have the `featuretteLoading` property), clone it again, and then we're in the infinite loop.

It's confusing, and I'm probably not explaining it well. Hopefully the new test and the `Clone` object do a better job of showing what we're running in to.

**Comment by commondream** [comment]
You're explaining it well. What I'm saying though is the clone and destroy puts it outside of what Featurette's supposed to do. I'd write the code some other way.

**Comment by anolson** [comment]
Let me see if I can provide a little more context around this issue.  We have a Featurette that wraps a [mediaelement](https://github.com/johndyer/mediaelement) object.  

Part of the [initialization](https://github.com/johndyer/mediaelement/blob/e502852176f610cbaf688d3ba50107d3f305e25d/src/js/mep-player.js#L353-L360) includes a scenario similar to what @dustinbrownman is describing here.

A patch to mediaelement was just merged that addresses this:
https://github.com/johndyer/mediaelement/commit/2a25cc5d921635836862a4e4ff1df0a161bf1966
 
From our perspective the bug has been fixed, but it's possible that someone else might run into this type of thing again.  It might be worth fixing it here as well.

**Comment by commondream** [comment]
I get what you’re saying, but removing the DOM element that a featurette is bound to, cloning, and then re-inserting it isn’t something that’s intended to be handled well by featurette. Doing so could have unintended consequences for anyone thinking it should be a new copy of the element.

**Comment by dustinbrownman** [comment]
I think that's a fair assessment, @commondream. Thank you for your time and feedback!

**Pull request closed without merging**
